---
# Filename
csv-filename: data-logger.csv

#Serial port config
serial:
  name: /dev/ttyACM0
  baudrate: 115200
  timeout: 0.1
  stopbit: 1
  parity: N
  bytesize: 8

# Start and end byte of the transfer
soi: 0xFF
eoi: 0xFB
# size of byte user want to send include soi(1),eoi(1),checksum(1), size(2), info(user-defined)
total_number_receive: 13

#Write according to arrival sequence
#data-type available:
# float,
# uint8_t, uint16_t, uint32_t,
# int8_t, int16_t, int32_t
data-logging:
  data1:
    name: float_data
    type: float
  data2:
    name: tick
    type: uint32_t
  # data3:
  #   name: data3
  #   type: uint8_t
  # data4:
  #   name: data4
  #   type: uint8_t

